[package]
name = "identity_stronghold"
version = "1.3.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "storage", "identity", "kms", "stronghold"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true
description = "Secure JWK storage with Stronghold for IOTA Identity"

[dependencies]
async-trait = { version = "0.1.64", default-features = false }
bls12_381_plus = { workspace = true, optional = true }
identity_storage = { version = "=1.3.0", path = "../identity_storage", default_features = false }
identity_verification = { version = "=1.3.0", path = "../identity_verification", default_features = false }
iota-crypto = { version = "0.23", default-features = false, features = ["ed25519"] }
iota-sdk = { version = "1.1.5", default-features = false, features = ["client", "stronghold"] }
iota_stronghold = { version = "2.1.0", default-features = false }
json-proof-token = { workspace = true, optional = true }
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
tokio = { version = "1.29.0", default-features = false, features = ["macros", "sync"] }
zeroize = { version = "1.6.0", default_features = false }
zkryptium = { workspace = true, optional = true }

[dev-dependencies]
anyhow = "1.0.82"
bls12_381_plus = { workspace = true }
identity_did = { version = "=1.3.0", path = "../identity_did", default_features = false }
identity_storage = { version = "=1.3.0", path = "../identity_storage", default_features = false, features = ["jpt-bbs-plus"] }
json-proof-token = { workspace = true }
tokio = { version = "1.29.0", default-features = false, features = ["macros", "sync", "rt"] }
zkryptium = { workspace = true }

[features]
default = []
# Enables `Send` + `Sync` bounds for the trait implementations on `StrongholdStorage`.
send-sync-storage = ["identity_storage/send-sync-storage"]
bbs-plus = ["identity_storage/jpt-bbs-plus", "dep:zkryptium", "dep:bls12_381_plus", "dep:json-proof-token"]

[lints]
workspace = true
