[package]
name = "identity_sui_name_tbd"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "identity", "sui"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true
description = "SUI related tooling for identity-rs"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.81"
bcs = "0.1.4"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "fastcrypto-zkp-v0.1.3", package = "fastcrypto" }
futures = { version = "0.3", default-features = false }
identity_core = { version = "=1.2.0", path = "../identity_core" }
identity_credential = { version = "=1.2.0", path = "../identity_credential", default-features = false }
identity_document = { version = "=1.2.0", path = "../identity_document" }
identity_eddsa_verifier = { version = "=1.2.0", path = "../identity_eddsa_verifier" }
identity_jose = { version = "=1.2.0", path = "../identity_jose" }
identity_verification = { version = "=1.2.0", path = "../identity_verification" }
iota-crypto = { version = "0.23" }
itertools = "0.13.0"
rand = "0.8.5"
secret-storage = { git = "https://github.com/iotaledger/secret-storage.git", branch = "proposal-for-changes" }
serde.workspace = true
serde-aux = "4.5.0"
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
identity_iota_core = { version = "=1.2.0", path = "../identity_iota_core" }
iota-config = { git = "https://github.com/iotaledger/iota.git", package = "iota-config" }
iota-sdk = { git = "https://github.com/iotaledger/iota.git", package = "iota-sdk" }
move-core-types = { git = "https://github.com/iotaledger/iota.git", package = "move-core-types", version = "0.0.4" }
shared-crypto = { git = "https://github.com/iotaledger/iota.git", package = "shared-crypto" }
tokio = { version = "1.29.0", default-features = false, features = ["macros", "sync", "rt", "process"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
eyre = { version = "0.6" }
fastcrypto-zkp = { git = "https://github.com/MystenLabs/fastcrypto", rev = "fastcrypto-zkp-v0.1.3", package = "fastcrypto-zkp" }
hex = { version = "0.4" }
identity_iota_core = { version = "=1.2.0", path = "../identity_iota_core", default-features = false, features = ["client"] }
jsonrpsee = { version = "0.24", default-features = false, features = ["wasm-client"] }
leb128 = { version = "0.2" }
num-bigint = { version = "0.4" }
primitive-types = { version = "0.12", features = ["impl-serde"] }
ref-cast = { version = "1.0" }
serde_repr = { version = "0.1" }
serde_with = { version = "2.3", features = ["hex"] } # Version 3 is incompatable with fastcrypto
tokio = { version = "1.29.0", default-features = false, features = ["macros", "sync", "rt"] }
tracing = { version = "0.1.40" }
uint = { version = "0.9" }

[dev-dependencies]
bcs = "0.1.4"
identity_credential = { version = "=1.2.0", path = "../identity_credential", features = ["validator"] }
identity_storage = { path = "../identity_storage", features = ["send-sync-storage", "storage-signer"] }
jsonpath-rust = "0.5.1"
serial_test = "3.1.1"

[lints]
workspace = true
