[package]
name = "identity_sui_name_tbd"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "identity", "sui"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true
description = "SUI related tooling for identity-rs"

[dependencies]
anyhow = "1.0.75"
# identity_stronghold = { path = "../identity_stronghold", default-features = false }
futures = { version = "0.3", default-features = false }
iota-sdk = { version = "1.0", default-features = false, features = ["tls", "client", "stronghold"] }
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
sui-sdk = { git = "https://github.com/iotaledger/kinesis.git", package = "sui-sdk" }
thiserror.workspace = true
tokio = { version = "1.29.0", default-features = false, features = ["macros", "sync", "rt", "process"] }

[dev-dependencies]
bcs = "0.1.4"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "d7a33a9f79271bfc19fc4c8816ea5467e4205e17" }
shared-crypto = { git = "https://github.com/iotaledger/kinesis.git", package = "shared-crypto" }
jsonpath-rust = "0.5.1"
serial_test = "3.1.1"

[lints]
workspace = true
