[workspace]
resolver = "2"
members = [
  # "identity_comm",
  "identity_account",
  "identity_account_storage",
  "identity_agent",
  "identity_core",
  "identity_credential",
  "identity_did",
  "identity_diff",
  "identity_iota",
  "identity_iota_client_legacy",
  "identity_iota_core_legacy",
  "identity_iota_core",

  "examples_legacy",
  "examples",
]

exclude = ["bindings/stronghold-nodejs", "bindings/wasm", "libjose"]

[profile.dev]
split-debuginfo = "unpacked"

# TODO: Temporary iota-crypto fix.
[patch.crates-io]
iota-crypto = { git = "https://github.com/iotaledger/crypto.rs/", rev = "43196de5cdf320b000963165c0da252ee738f190" }
