[workspace]
resolver = "2"
members = [
  "identity_core",
  "identity_credential",
  "identity_did",
  "identity_document",
  "identity_iota",
  "identity_storage",
  "identity_iota_core",
  "identity_resolver",
  "identity_verification",
  "identity_stronghold",
  "identity_jose",
  "identity_eddsa_verifier",
  "examples",
]

exclude = ["bindings/wasm"]

[workspace.dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
thiserror = { version = "1.0", default-features = false }
strum = { version = "0.25", default-features = false, features = ["std", "derive"] }
serde_json = { version = "1.0", default-features = false }
json-proof-token = { version = "0.3.5" }
zkryptium = { version = "0.2.1", default-features = false, features = ["bbsplus"] }

[workspace.package]
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
license = "Apache-2.0"
repository = "https://github.com/iotaledger/identity.rs"
rust-version = "1.65"

[patch.crates-io]
iota_stronghold = {git = "https://github.com/tensor-programming/stronghold.rs.git", branch = "feat/expose_runner"}