[workspace]
resolver = "2"
members = [
  "identity_agent",
  # "identity_comm",
  "identity_core",
  "identity_credential",
  "identity_did",
  "identity_diff",
  "identity_document", 
  "identity_iota",
  "identity_iota_core",
  "identity_resolver",
  "examples",
]

exclude = [
  "identity_iota_core_legacy",
  "bindings/stronghold-nodejs",
  "bindings/wasm",
  "libjose",
]

[profile.dev]
split-debuginfo = "unpacked"

[workspace.dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
thiserror = { version = "1.0", default-features = false }