[workspace]
resolver = "2"
members = [
  "identity",
  "identity-comm",
  "identity-account",
  "identity-core",
  "identity-credential",
  "identity-did",
  "identity-diff",
  "identity-iota",
  "identity-iota-core",
  "identity-account-core",

  "examples",
]

exclude = [
  "bindings/wasm",
  "libjose",
]

[profile.dev]
split-debuginfo = "unpacked"
