[workspace]
members = [
  "identity",
  "identity-account",
  "identity-core",
  "identity-credential",
  "identity-did",
  "identity-diff",
  "identity-iota",
  "bindings/wasm",
  "examples",
]

exclude = [
  "libjose",
]
