[workspace]
resolver = "2"
members = [
  # "identity_comm",
  "identity_account",
  "identity_account_storage_legacy",
  "identity_agent",
  "identity_core",
  "identity_credential",
  "identity_did",
  "identity_diff",
  "identity_iota",
  "identity_iota_client_legacy",
  "identity_iota_core_legacy",
  "identity_stardust",

  "examples_legacy",
  "examples",
]

exclude = ["bindings/stronghold-nodejs", "bindings/wasm", "libjose"]

[profile.dev]
split-debuginfo = "unpacked"
