[workspace]
members = [
  "identity",
  "identity-account",
  "identity-core",
  "identity-credential",
  "identity-did",
  "identity-diff",
  "identity-iota",

  "libjose",
  "examples",
]

exclude = [
  "bindings/wasm",
]
