[workspace]
resolver = "2"
members = [
  # "identity_comm",
  "identity_core",
  "identity_credential",
  "identity_did",
  "identity_diff",
  "identity_iota",
  "identity_iota_core",
  "identity_resolver",
  "examples",
]

exclude = [
  "identity_account",
  "identity_account_storage",
  "identity_agent",
  "examples_legacy",
  "identity_iota_core_legacy",
  "bindings/stronghold-nodejs",
  "bindings/wasm",
  "libjose",
]

[profile.dev]
split-debuginfo = "unpacked"
