[workspace]
resolver = "2"
members = [
  "identity",
  # "identity_comm",
  "identity_account",
  "identity_account_storage",
  "identity-core",
  "identity-credential",
  "identity-did",
  "identity_diff",
  "identity_iota_client",
  "identity_iota_core",

  "examples",
]

exclude = [
  "bindings/stronghold-nodejs",
  "bindings/wasm",
  "libjose",
]

[profile.dev]
split-debuginfo = "unpacked"
