[workspace]
members = [
    "identity_account",
    "identity_communication",
    "identity_resolver",
    "identity_schema",
    "identity_core",
    "identity_integration",
    "identity_vc",
    "identity_crypto"
]
