[workspace]
members = [
    "identity_account",
    "identity_communication",
    "identity_resolver",
    "identity_schema",
    "identity_common",
    "identity_core",
    "identity_crypto",
    "identity_integration",
    "identity_proof",
    "identity_vc",
    "identity_diff",
    "identity_derive"
]
