[package]
name = "identity_crypto"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "Cryptography Utilities for Identities"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# error handling
thiserror = "1.0"
anyhow = "1.0"

# serialization
cjson = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# crypto
ed25519-dalek = "1.0"
libsecp256k1 = "0.3"
sha2 = "0.9"

# utilities
base64 = "0.12"
hex = "0.4"
lazy_static = "1.4"
rand = "0.7"
zeroize = "1.1"

identity_core = { path = "../identity_core" }
# identity_core = { git = "https://github.com/iotaledger/identity.rs", branch = "feat/common-core-types" }
