[package]
name = "identity_core"
version = "1.6.0-alpha"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "tangle", "identity"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
description = "The core traits and types for the identity-rs library."

[dependencies]
# pin dependency of `time` and limit range, as `0.4.1` has impl for `usize: PartialOrd<_>`
# that conflicts with `iota-sdk`s `core` impl, leading to errors in `iota-sdk` crate
deranged = { version = ">=0.4.0, <0.4.1", default-features = false }
multibase = { version = "0.9", default-features = false, features = ["std"] }
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
strum.workspace = true
thiserror.workspace = true
time = { version = "0.3.23", default-features = false, features = ["std", "serde", "parsing", "formatting"] }
url = { version = "2.4", default-features = false, features = ["serde"] }

[target.'cfg(all(target_arch = "wasm32", not(target_os = "wasi")))'.dependencies]
js-sys = { version = "0.3.55", default-features = false, optional = true }

[dev-dependencies]
proptest = { version = "1.0.0" }
quickcheck = { version = "1.0" }
quickcheck_macros = { version = "1.0" }

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps --workspace --open
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[features]
default = ["dep:js-sys"]
# Enables a macro to provide a custom time (Timestamp::now_utc) implementation, see src/custom_time.rs
custom_time = []

[[test]]
name = "custom_time"
required-features = ["custom_time"]
