[package]
name = "identity_core"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "An implementation of the Decentralized Identifiers (DID) standard"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# error handling
thiserror = "1.0"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
derive_builder = { version = "0.9", default-features = false }
percent-encoding = { version = "2.1", default-features = false }
url = { version = "2.1", default-features = false, features = ["serde"] }

# serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }

# diff macro and trait
identity_diff = { path = "../identity_diff", version = "0.1.0", features = ["diff_derive"] }

# parser crates
pest = "2.1"
pest_derive = "2.1"

# trait
async-trait = "0.1"

[dev-dependencies]
# generative/property testing
proptest = "0.10"

# serde testing
serde_test = "1.0"

# json parsing
json = "0.12"
