[package]
name = "identity-core"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "The core traits and types for the identity-rs library."
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
base64 = { version = "0.13", default-features = false, features = ["std"] }
bs58 = { version = "0.4", default-features = false, features = ["std"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
digest = { version = "0.9", default-features = false }
ed25519-zebra = { version = "2.2", default-features = false }
erased-serde = { version = "0.3", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false }
identity-diff = { version = "=0.1.0", path = "../identity-diff", default-features = false }
rand = { version = "0.7", default-features = false, features = ["alloc", "getrandom"] }
roaring = { version = "0.6", default-features = false }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
serde_jcs = { version = "0.1", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["preserve_order", "std"] }
sha2 = { version = "0.9", default-features = false }
subtle = { version = "2.4" }
thiserror = { version = "1.0", default-features = false }
url = { version = "2.2", default-features = false, features = ["serde"] }
zeroize = { version = "1.2", default-features = false }
