name: 'setup-sccache-windows'
description: 'Setup sccache for windows.'
runs:
  using: "composite"
  steps:
    - name: Install sccache (windows-latest)
      shell: pwsh
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop install sccache
        echo "${HOME}/scoop/apps/sccache/current" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Start sccache
      shell: pwsh
      run: |
        sccache --start-server
        sccache -s