name: 'setup-sccache-windows'
description: 'Setup sccache for windows.'
runs:
  using: "composite"
  steps:
    - name: Install sccache (windows-latest)
      shell: pwsh
      run: |
        choco install sccache
    
    - name: Start sccache
      shell: pwsh
      run: |
        sccache --start-server
        sccache -s