name: 'get-current-date-ubuntu-macos'
description: 'Script for getting the current date on ubuntu and macos.'
runs:
  using: "composite"
  steps:
    - name: Get current date
      shell: sh
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV