[package]
name = "identity_credential"
version = "0.7.0-alpha.3"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity"]
license = "Apache-2.0"
readme = "./README.md"
repository = "https://github.com/iotaledger/identity.rs"
rust-version = "1.62"
description = "An implementation of the Verifiable Credentials standard."

[dependencies]
erased-serde = { version = "0.3.21", default-features = false, features = ["std"], optional = true }
identity_core = { version = "=0.7.0-alpha.3", path = "../identity_core", default-features = false }
identity_did = { version = "=0.7.0-alpha.3", path = "../identity_did", default-features = false }
itertools = { version = "0.10", default-features = false, features = ["use_std"], optional = true }
lazy_static = { version = "1.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
serde_repr = { version = "0.1", default-features = false, optional = true }
strum = { version = "0.24.0", default-features = false, features = ["std", "derive"] }
thiserror = { version = "1.0", default-features = false }

[dev-dependencies]
proptest = { version = "1.0.0", default-features = false, features = ["std"] }
serde_json = { version = "1.0", default-features = false }

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps --workspace --open
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["revocation-bitmap", "validator"]
revocation-bitmap = ["identity_did/revocation-bitmap"]
validator = ["dep:itertools", "dep:erased-serde", "dep:serde_repr"]
