[package]
name = "identity_storage"
version = "0.7.0-alpha.4"
edition = "2021"

[dependencies]
async-trait = "0.1"
identity_core = { version = "=0.7.0-alpha.4", path = "../identity_core", default-features = false }
identity_credential = { version = "=0.7.0-alpha.4", path = "../identity_credential", default-features = false }
# identity_data_integrity = { version = "=0.7.0-alpha.4", path = "../identity_data_integrity", default-features = false }
identity_did = { version = "=0.7.0-alpha.4", path = "../identity_did", default-features = false }
identity_jose = { version = "=0.7.0-alpha.4", path = "../identity_jose", default-features = false }
iota-crypto = { version = "0.15", default-features = false, features = ["blake2b", "ed25519", "random"], optional = true }
rand = { version = "0.8.5", default-features = false, features = ["std"], optional = true }
serde = "1.0.145"
serde_json = "1.0.86"
thiserror = "1"
tokio = { version = "1.23.0", default-features = false, features = ["macros", "sync"], optional = true }

[dev-dependencies]
rand = { version = "0.8.5" }
tokio = { version = "1.23.0", default-features = false, features = ["macros", "sync", "rt"] }

[features]
memstore = ["dep:tokio", "dep:rand", "dep:iota-crypto"]
