blank_issues_enabled: false
contact_links:
  - name: Official IOTA Discord
    url: https://discord.com/channels/397872799483428865/443602228813627392
    about: "Contact the maintainers by joining the #identity channel on the IOTA Discord."
