name: 'install-and-start-sccache-macos'
description: ''
runs:
  using: "composite"
  steps:
    - name: Install sccache (macos-latest)
      shell: sh
      run: |
        brew update --preinstall
        brew install sccache
        
    - name: Start sccache
      shell: sh
      run: |
        sccache --start-server
        sccache -s