name: 'install-and-start-sccache-windows'
description: ''
inputs:
  cache-path:
    description: ''
    required: true
  cache-key:
    description: ''
    required: true
  cache-restore-keys:
    description: ''
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache sccache
      uses: actions/cache@v2.1.6
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}
        restore-keys: ${{ inputs.cache-restore-keys }}

    - name: Install sccache (windows-latest)
      shell: pwsh
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop install sccache
        echo "${HOME}/scoop/apps/sccache/current" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Start sccache
      shell: pwsh
      run: |
        sccache --start-server
        sccache -s