[package]
name = "identity-comm"
version = "0.2.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A DID communication library"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
identity-core = { path = "../identity-core", version = "=0.2.0" }
identity-did = { path = "../identity-did", version = "=0.2.0" }
identity-iota = { path = "../identity-iota", version = "=0.2.0" }
libjose = { git = "https://github.com/iotaledger/identity.rs", branch = "dev" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = { version = "1.0" }
uuid = { version = "0.8", features = ["serde", "v4"]}
