[package]
name = "identity_comm"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A DID communication library"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
async-std = "1.9.0"
futures-util = "0.3.14"
futures = "0.3.14"
identity-account = { path = "../identity-account", version = "=0.2.0" }
identity-core = { path = "../identity-core", version = "=0.2.0" }
identity-did = { path = "../identity-did", version = "=0.2.0" }
identity-iota = { path = "../identity-iota", version = "=0.2.0" }
# libjose = { path = "../libjose", version = "=0.1.0" }
libjose = { git = "https://github.com/iotaledger/identity.rs", rev = "2d98050068b9f60b06468536ada30597d60b99f3" }
riker = "0.4.2"
riker-patterns = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = { version = "1.0" }
