name: 'setup-sccache-ubuntu'
description: 'Setup sccache for ubuntu.'
runs:
  using: "composite"
  steps:
    - name: Install sccache (macos-latest)
      shell: sh
      run: |
        SCCACHE_DOWNLOAD_LINK=https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION=v0.2.15
        SCCACHE_PREFIX="sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl"
        SCCACHE_TAR="${SCCACHE_PREFIX}.tar.gz"
        DOWNLOAD_LINK="${SCCACHE_DOWNLOAD_LINK}/${SCCACHE_VERSION}/${SCCACHE_TAR}"
        curl -L "${DOWNLOAD_LINK}" --output ${SCCACHE_TAR}
        echo "$(curl -L ${DOWNLOAD_LINK}.sha256)  ${SCCACHE_TAR}" | shasum -a 256 --check --status
        tar xzf ${SCCACHE_TAR}
        BIN_DIR="$HOME/.local/bin"
        mkdir -p ${BIN_DIR}
        mv -f ${SCCACHE_PREFIX}/sccache ${BIN_DIR}/sccache
        chmod a+x "${BIN_DIR}/sccache"
        echo ${BIN_DIR} >> $GITHUB_PATH
        
    - name: Start sccache
      shell: sh
      run: |
        sccache --start-server
        sccache -s