[package]
name = "identity_diff"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A library for diffing Rust Structs"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[features]
default = ["serde_value"]
serde_value = ["serde_json"]
diff_derive = ["identity_derive"]

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
serde_json = {version = "1.0", optional = true }

# error handling
anyhow = "1.0"
thiserror = "1.0"

identity_derive = {version = "0.1.0", path = "../identity_derive", optional = true}

did_doc = { git = "https://github.com/l1h3r/did_doc", rev = "c61c0457eea7a453949a877f1dde92878a23dd24", default-features = false, features = ["std"] }
did_url = { version = "0.1", default-features = false, features = ["std", "serde"] }

[dev-dependencies]
serde_json = "1.0"
