name: 'bump-versions'
description: 'Bump versions in files for release target'
inputs:
  release-target:
    description: "target of the release (rust|wasm)"
    required: true
  version:
    description: "release name"
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-release
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-release

    - name: Install cargo-edit # to use cargo add
      uses: actions-rs/cargo@v1
      if: ${{inputs.release-target == 'rust'}}
      with:
        command: install
        args: cargo-edit

    - name: Replace identity (dev) version in Wasm bindings
      shell: bash
      if: ${{inputs.release-target == 'rust'}}
      working-directory: bindings/wasm
      run: |
        cargo add identity@=${{ inputs.version }} --path=../../identity

    - name: Commit changes
      shell: bash
      if: ${{inputs.release-target == 'rust'}}
      run: |
        git add .
        if [[ $(git diff --stat --staged) == '' ]]; then
          echo 'repository unmodified'
          exit 1
        fi
        git commit -m "Bump Wasm Identity dependency version"
    
    - name: Bump Rust (dev) version
      shell: bash
      # cargo-release creates a signed commit automatically
      if: ${{inputs.release-target == 'rust'}}
      run: |
        cargo release --workspace --config ./release.toml --no-tag --no-publish --no-push --no-confirm ${{ inputs.version }} --execute

    - name: Bump Wasm bindings (dev) version
      shell: bash
      # cargo-release creates a signed commit automatically
      if: ${{inputs.release-target == 'wasm'}}
      working-directory: bindings/wasm
      run: |
        cargo release --no-tag --no-publish --no-push --no-confirm ${{ inputs.version }} --execute

    - name: Set up Node.js
      uses: actions/setup-node@v2
      if: ${{inputs.release-target == 'wasm'}}
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Bump Wasm npm package (dev) version
      shell: bash
      if: ${{inputs.release-target == 'wasm'}}
      working-directory: bindings/wasm
      run: |
        npm version ${{ inputs.version }}

    - name: Commit npm package version
      shell: bash
      if: ${{inputs.release-target == 'wasm'}}
      run: |
        git add .
        if [[ $(git diff --stat --staged) == '' ]]; then
          echo 'repository unmodified'
          exit 1
        fi
        git commit -m "Bump npm package version"