[package]
name = "examples"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
identity = { path = "../identity", features = ["account"] }
pretty_env_logger = { version = "0.4" }
rand = { version = "0.8" }
tokio = { version = "1.5", features = ["full"] }

[[example]]
name = "getting_started"
path = "getting_started.rs"

[[example]]
name = "low_create_did"
path = "low-level-api/create_did.rs"

[[example]]
name = "low_manipulate_did"
path = "low-level-api/manipulate_did.rs"

[[example]]
name = "low_verifiable_credential"
path = "low-level-api/verifiable_credential.rs"

[[example]]
name = "low_verifiable_presentation"
path = "low-level-api/verifiable_presentation.rs"

[[example]]
name = "low_resolution"
path = "low-level-api/resolution.rs"

[[example]]
name = "low_diff_chain"
path = "low-level-api/diff_chain.rs"

[[example]]
name = "low_merkle_key"
path = "low-level-api/merkle_key.rs"

[[example]]
name = "account_basic"
path = "account/basic.rs"

[[example]]
name = "account_config"
path = "account/config.rs"

[[example]]
name = "account_methods"
path = "account/methods.rs"

[[example]]
name = "account_services"
path = "account/services.rs"

[[example]]
name = "account_signing"
path = "account/signing.rs"

[[example]]
name = "account_stronghold"
path = "account/stronghold.rs"
