[package]
name = "examples"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
identity = { path = "../identity", features = ["account"] }
pretty_env_logger = { version = "0.4" }
rand = { version = "0.8" }
tokio = { version = "1.10", features = ["full"] }

[[example]]
name = "getting_started"
path = "getting_started.rs"

[[example]]
name = "account_basic"
path = "account/basic.rs"

[[example]]
name = "account_config"
path = "account/config.rs"

[[example]]
name = "account_methods"
path = "account/methods.rs"

[[example]]
name = "account_services"
path = "account/services.rs"

[[example]]
name = "account_signing"
path = "account/signing.rs"

[[example]]
name = "account_stronghold"
path = "account/stronghold.rs"

[[example]]
name = "account_private_tangle"
path = "account/private_tangle.rs"

[[example]]
name = "create_did"
path = "low-level-api/create_did.rs"

[[example]]
name = "create_vc"
path = "low-level-api/create_vc.rs"

[[example]]
name = "create_vp"
path = "low-level-api/create_vp.rs"

[[example]]
name = "diff_chain"
path = "low-level-api/diff_chain.rs"

[[example]]
name = "resolve_history"
path = "low-level-api/resolve_history.rs"

[[example]]
name = "manipulate_did"
path = "low-level-api/manipulate_did.rs"

[[example]]
name = "merkle_key"
path = "low-level-api/merkle_key.rs"

[[example]]
name = "resolution"
path = "low-level-api/resolution.rs"

[[example]]
name = "private_tangle"
path = "low-level-api/private_tangle.rs"

[[example]]
name = "revoke_vc"
path = "low-level-api/revoke_vc.rs"
