[package]
name = "StardustTest"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
# as we don't have the tag, reference to the respective commit hash
MoveStdlib = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/move-stdlib", rev = "develop" }
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "develop" }

[addresses]
stardust = "0x0"
