# Copyright (c) 2024 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0

[package]
name = "IotaIdentity"
edition = "2024"

[dependencies]

[addresses]
iota_identity = "0x0"
identity_team = "0x1d3c717" # TODO: replace this with the actual address of the identity team.

[dev-dependencies]

[dev-addresses]
