[package]
name = "identity-example-credential"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
publish = false

[dependencies]
identity-core = { path = "../../identity-core" }
identity-iota = { path = "../../identity-iota" }
smol = { version = "0.1.18", features = ["tokio02"] }
smol-potat = { version = "0.3" }
