[package]
name = "identity_verification"
version = "0.7.0-alpha.6"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Verification data types and functionality for identity.rs"

[dependencies]
identity_core = { version = "=0.7.0-alpha.6", path = "./../identity_core", default-features = false }
identity_did = { version = "=0.7.0-alpha.6", path = "./../identity_did", default-features = false }
identity_jose = { version = "=0.7.0-alpha.6", path = "./../identity_jose", default-features = false }
serde.workspace = true
strum.workspace = true
thiserror.workspace = true

[features]
diff = ["identity_core/diff", "identity_did/diff", "identity_jose/diff"]
# Enables jws verification based on the EdDSA algorithm.
eddsa = ["identity_jose/eddsa"]

[dev-dependencies]
serde_json.workspace = true
