[package]
name = "identity_vc"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "An implementation of the Verifiable Credentials (VC) standard"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[[bin]]
name = "vc_test_suite"
path = "bin/vc_test_suite.rs"

[[bin]]
name = "credential"
path = "bin/credential.rs"

[dependencies]
# error handling
thiserror = "1.0"
anyhow = "1.0"

# serialization
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_cbor = "0.11"

# timestamps
chrono = { version = "0.4", features = ["serde"] }

identity_core = { git = "https://github.com/iotaledger/identity.rs", branch = "feat/common-core-types" }
identity_crypto = { git = "https://github.com/iotaledger/identity.rs", branch = "feat/identity-crypto" }
