name: 'build-and-test'
description: ''
runs:
  using: "composite"
  steps:
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true