name: 'private-tangle-setup'
description: 'Setup a private tangle'
runs:
  using: "composite"
  steps:
    - name: Setup private tangle
      shell: bash
      run: |
        git clone --depth=1 https://github.com/iotaledger/hornet.git
        cd hornet/private_tangle
        jq '.restApi.pow.enabled = $newVal' --arg newVal false config_private_tangle.json > tmp.$$.json && mv tmp.$$.json config_private_tangle.json
        jq --color-output . config_private_tangle.json
        sudo ./cleanup.sh
        sudo ./bootstrap.sh
        sudo ./run.sh -d
    - name: Wait for tangle to start
      shell: bash
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- -t 60 http://localhost:14265/health -- echo "Tangle is up"
      env:
        WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
    - name: Wait for faucet to start
      shell: bash
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- -t 60 http://localhost:8091/api/info -- echo "Faucet is up"
      env:
        WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
