name: 'private-tangle-setup'
description: 'Setup a private tangle'
runs:
  using: "composite"
  steps:
    - name: Setup private tangle
      shell: bash
      run: |
        # Download the private_tangle setup from the hornet repo.
        mkdir private_tangle
        cd private_tangle
        # Use the outpt of https://api.github.com/repos/iotaledger/hornet/releases/latest once we have a 2.0 Hornet release.
        RELEASE_ID=$(curl "https://api.github.com/repos/iotaledger/hornet/releases" | jq -r .[0].tag_name)
        curl -L -O "https://github.com/iotaledger/hornet/releases/download/${RELEASE_ID}/HORNET-${RELEASE_ID}-private_tangle.tar.gz"
        tar -xf HORNET-${RELEASE_ID}-private_tangle.tar.gz

        # Manipulate and print config
        jq '.restAPI.pow.enabled = $newVal' --argjson newVal false config_private_tangle.json > tmp.$$.json && mv tmp.$$.json config_private_tangle.json
        jq --color-output . config_private_tangle.json
        
        # Start Tangle
        sudo ./cleanup.sh
        sudo ./bootstrap.sh
        sudo ./run.sh -d
    - name: Wait for tangle to start
      shell: bash
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- -t 60 http://localhost:14265/health -- echo "Tangle is up"
      env:
        WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
    - name: Wait for faucet to start
      shell: bash
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- -t 60 http://localhost:8091/api/info -- echo "Faucet is up"
      env:
        WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
