[package]
name = "identity_iota_core"
version = "0.7.0-alpha.3"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "utxo", "shimmer", "identity"]
license = "Apache-2.0"
readme = "./README.md"
repository = "https://github.com/iotaledger/identity.rs"
rust-version = "1.62"
description = "An IOTA Ledger integration for the IOTA DID Method."

[dependencies]
identity_core = { version = "=0.7.0-alpha.3", path = "../identity_core", default-features = false }
identity_credential = { version = "=0.7.0-alpha.3", path = "../identity_credential", default-features = false, features = ["validator"] }
identity_did = { version = "=0.7.0-alpha.3", path = "../identity_did", default-features = false }
# Pin until iota-client v2.0.1-rc.4 is released
iota-types = { version = "=1.0.0-rc.1", default-features = false, features = ["block", "std"], optional = true }

async-trait = { version = "0.1.56", default-features = false, optional = true }
futures = { version = "0.3" }
iota-client = { version = "2.0.1-rc.3", default-features = false, features = ["tls"], optional = true }
num-derive = { version = "0.3", default-features = false }
num-traits = { version = "0.2", default-features = false, features = ["std"] }
once_cell = { version = "1", default-features = false, features = ["std"] }
prefix-hex = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
strum = { version = "0.21", features = ["derive"] }
thiserror = { version = "1.0", default-features = false }

[dev-dependencies]
anyhow = { version = "1.0.57" }
iota-crypto = { version = "0.12.1", default-features = false, features = ["bip39", "bip39-en"] }
proptest = { version = "1.0.0", default-features = false, features = ["std"] }
tokio = { version = "1.17.0", default-features = false, features = ["rt-multi-thread", "macros"] }

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps --workspace --open
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["client", "iota-client", "revocation-bitmap", "send-sync-client-ext"]
# Exposes the `IotaIdentityClient` and `IotaIdentityClientExt` traits.
client = ["dep:async-trait", "dep:iota-types"]
# Enables the iota-client dependency, the client trait implementations for it, and the `IotaClientExt` trait.
iota-client = ["dep:iota-client", "client"]
# Enables revocation with `RevocationBitmap2022`.
revocation-bitmap = ["identity_did/revocation-bitmap"]
# Adds Send bounds on the futures produces by the client extension traits.
send-sync-client-ext = []
