name: 'rust-setup'
description: ''
inputs:
  sccache-path:
    description: ''
    required: true
  os:
    description: ''
    required: true
  job:
    description: ''
    required: true
  current-date:
    description: ''
    required: true
  target-cache-path:
    description: ''
    required: false
    default: target
runs:
  using: "composite"
  steps:
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache cargo
      uses: actions/cache@v2.1.4
      with:
        # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        # Add date to the cache to keep it up to date
        key: ${{ inputs.os }}-cargo-${{ inputs.job }}-${{ hashFiles('**/Cargo.toml') }}-${{ inputs.current-date }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ inputs.os }}-cargo-${{ inputs.job }}-${{ hashFiles('**/Cargo.toml') }}-
          ${{ inputs.os }}-cargo-${{ inputs.job }}-
          ${{ inputs.os }}-cargo-

    # Generate Cargo.lock files for build, sccache cache keys.
    # Allows dependencies updated on crates.io between runs to trigger storing an updated cache,
    # which hashing Cargo.toml files alone does not.
    - name: Cargo update
      uses: actions-rs/cargo@v1
      with:
        command: update

    - name: Cache build target
      uses: actions/cache@v2.1.4
      with:
        path: ${{ inputs.target-cache-path }}
        # Add date to the cache to keep it up to date
        key: ${{ inputs.os }}-target-${{ inputs.job }}-${{ hashFiles('**/Cargo.lock') }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ inputs.os }}-target-${{ inputs.job }}-
          ${{ inputs.os }}-target-

    - name: Cache sccache
      uses: actions/cache@v2.1.6
      with:
          path: ${{ inputs.sccache-path }}
          key: ${{ inputs.os }}-sccache-${{ inputs.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ inputs.os }}-sccache-${{ inputs.job }}-
            ${{ inputs.os }}-sccache-