[package]
name = "identity_resolver"
version = "0.7.0-alpha.3"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "did", "identity", "resolver", "resolution"]
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
rust-version = "1.62"
description = "DID Resolution utilities for the identity.rs library."

[dependencies]
# This is currently necessary for the ResolutionHandler trait. This can be made an optional dependency if alternative ways of attaching handlers are introduced.
async-trait = { version = "0.1", default-features = false }
futures = { version = "0.3" }
identity_core = { version = "=0.7.0-alpha.3", path = "../identity_core", default-features = false }
identity_credential = { version = "=0.7.0-alpha.3", path = "../identity_credential", default-features = false, features = ["validator"] }
identity_did = { version = "=0.7.0-alpha.3", path = "../identity_did", default-features = false }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
strum = { version = "0.21", features = ["derive"] }
thiserror = { version = "1.0", default-features = false }

[dependencies.identity_iota_core]
version = "=0.7.0-alpha.3"
path = "../identity_iota_core"
default-features = false
features = ["send-sync-client-ext", "iota-client"]
optional = true

[dev-dependencies]
iota-client = { version = "2.0.1-rc.1", default-features = false, features = ["tls"] }
tokio = { version = "1.17.0", default-features = false, features = ["rt-multi-thread", "macros"] }

[features]
default = ["revocation-bitmap", "iota"]
revocation-bitmap = ["identity_did/revocation-bitmap", "identity_iota_core?/revocation-bitmap"]
# Enables the IOTA integration for the resolver.
iota = ["dep:identity_iota_core"]
