[package]
name = "identity_resolver"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "Did Resolution Library"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# error handling
thiserror = "1.0"
anyhow = "1.0"

# serialization
serde = "1.0"
serde_json = "1.0"
serde-diff = "0.3.1"

percent-encoding = "2.1.0"
url = "2.1.1"

iota-conversion =  "0.5.1"
# identity_core = {git = "https://github.com/iotaledger/identity.rs", branch = "dev"}
identity_core = {git = "https://github.com/iotaledger/identity.rs", branch = "feat(core)/solidify-api-and-diff"}
identity_integration = {git = "https://github.com/iotaledger/identity.rs", branch = "feat/did-ledger-integration"}

[dev-dependencies]
smol-potat = "0.3.3"
smol = {version = "0.1.18", features = ["tokio02"] }
