[package]
name = "identity_stardust"
version = "0.6.0"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "stardust", "identity"]
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
rust-version = "1.62"
description = "An IOTA Ledger integration for the identity.rs library."
[workspace]

[dependencies]
# Ensure bee-block always matches the version used by iota-client.
bee-block = { version = "1.0.0-beta.5", default-features = false, features = ["std"], optional = true }
identity_core = { version = "=0.6.0", path = "../identity_core", default-features = false }
identity_credential = { version = "=0.6.0", path = "../identity_credential", default-features = false }
identity_did = { version = "=0.6.0", path = "../identity_did", default-features = false }

async-trait = { version = "0.1.56", default-features = false, optional = true }
num-derive = { version = "0.3", default-features = false }
num-traits = { version = "0.2", default-features = false, features = ["std"] }
once_cell = { version = "1", default-features = false, features = ["std"] }
prefix-hex = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
strum = { version = "0.21", features = ["derive"] }
thiserror = { version = "1.0", default-features = false }

[dependencies.iota-client]
git = "https://github.com/iotaledger/iota.rs"
rev = "a582bfa882793fe21db2055c4f7878ebc531877a" # develop branch, 2022-07-27
features = ["tls"]
default-features = false
optional = true

[dev-dependencies]
anyhow = { version = "1.0.57" }
iota-crypto = { version = "0.12.1", default-features = false, features = ["bip39", "bip39-en"] }
proptest = { version = "1.0.0", default-features = false, features = ["std"] }
tokio = { version = "1.17.0", default-features = false, features = ["rt-multi-thread", "macros"] }

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps --workspace --open
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["client", "iota-client", "revocation-bitmap"]
# Exposes the `StardustIdentityClient` and `StardustIdentityClientExt` traits.
client = ["dep:async-trait", "dep:bee-block"]
# Enables the iota-client dependency, the client trait implementations for it, and the `StardustClientExt` trait.
iota-client = ["dep:iota-client", "client"]
# Enables revocation with `RevocationBitmap2022`.
revocation-bitmap = ["identity_did/revocation-bitmap"]
