name: 'private-tangle-tear-down'
description: 'tear-down a private tangle'
runs:
  using: "composite"
  steps:
    - name: Tear down private tangle
      shell: bash
      run: |
        cd private_tangle
        docker-compose down
        cd ..
        sudo rm -rf private_tangle
