[package]
name = "identity_ecdsa_verifier"
version = "1.3.1"
authors = ["IOTA Stiftung", "Filancore GmbH"]
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "identity", "jose", "jwk", "jws"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true
description = "JWS ECDSA signature verification for IOTA Identity"

[lints]
workspace = true

[dependencies]
identity_verification = { version = "=1.3.1", path = "../identity_verification", default-features = false }
k256 = { version = "0.13.3", default-features = false, features = ["std", "ecdsa", "ecdsa-core"], optional = true }
p256 = { version = "0.13.2", default-features = false, features = ["std", "ecdsa", "ecdsa-core"], optional = true }
signature = { version = "2", default-features = false }

[dev-dependencies]
josekit = "0.8.6"
serde_json.workspace = true

[features]
default = ["es256", "es256k"]
# Enables the EcDSAJwsVerifier to verify JWS with alg = ES256.
es256 = ["dep:p256"]
# Enables the EcDSAJwsVerifier to verify JWS with alg = ES256K.
es256k = ["dep:k256"]
