[package]
name = "identity_document"
version = "0.7.0-alpha.5"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "tangle", "identity", "did"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true
description = "Method-agnostic implementation of the Decentralized Identifiers (DID) standard."

[dependencies]
did_url = { version = "0.1", default-features = false, features = ["std", "serde"] }
form_urlencoded = { version = "1.0.1", default-features = false }
identity_core = { version = "=0.7.0-alpha.5", path = "../identity_core" }
identity_did = { version = "=0.7.0-alpha.5", path = "../identity_did" }
identity_verification = { version = "=0.7.0-alpha.5", path = "../identity_verification", default-features = false }
indexmap = { version = "1.7", default-features = false, features = ["std", "serde-1"] }
serde.workspace = true
strum.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false, features = ["cargo_bench_support"] }
serde_json.workspace = true

[[bench]]
name = "deserialize_document"
harness = false
