[package]
name = "identity_document"
version = "0.7.0-alpha.4"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity", "did"]
license = "Apache-2.0"
readme = "./README.md"
repository = "https://github.com/iotaledger/identity.rs"
description = "Agnostic implementation of the Decentralized Identifiers (DID) standard."

[dependencies]
serde.workspace = true
thiserror.workspace = true
identity_did = { version = "=0.7.0-alpha.4", path = "../identity_did" }
dataurl = { version = "0.1.2", default-features = false, optional = true }
did_url = { version = "0.1", default-features = false, features = ["std", "serde"] }
flate2 = { version = "1.0.23", default-features = false, features = ["rust_backend"], optional = true }
form_urlencoded = { version = "1.0.1", default-features = false }
identity_core = { version = "=0.7.0-alpha.4", path = "../identity_core" }
indexmap = { version = "1.7", default-features = false, features = ["std", "serde-1"] }
roaring = { version = "0.9.0", default-features = false, optional = true }
strum = { version = "0.24.0", default-features = false, features = ["std", "derive"] }

[dev-dependencies]
serde_json = { version = "1.0", default-features = false }
criterion = { version = "0.4.0", default-features = false, features = ["cargo_bench_support"] }
[features]
default = ["revocation-bitmap"]
revocation-bitmap = ["dataurl", "flate2", "roaring"]

[[bench]]
name = "deserialize_document"
harness = false