[package]
name = "identity_iota"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A DID to ledger intergration library for IOTA"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# error handling
anyhow = "1.0"
thiserror = "1.0"

# serialization
serde = "1.0"
serde_json = "1.0"

# IOTA
iota-core = { git = "https://github.com/Thoralf-M/iota.rs", branch = "works" }
iota-conversion =  "0.5.1"
failure = "0.1.8"

# identity
identity_core = { path = "../identity_core" }
identity_crypto = {git = "https://github.com/iotaledger/identity.rs", branch = "feat/identity-signature-suites"}
libjose = {git = "https://github.com/iotaledger/identity.rs", branch = "feat/siop-did"}
identity_diff = { path = "../identity_diff" }

# hash
multihash = "*"
bs58 = "0.3.1"
hex = "0.4"

async-trait = "0.1.41"

[dev-dependencies]
smol-potat = "0.3.3"
smol = {version = "0.1.18", features = ["tokio02"] }
