[package]
name = "identity_iota"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A DID to ledger intergration library for IOTA"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
anyhow = { version = "1.0", default-features = false, features = ["std"] }
async-trait = { version = "0.1", default-features = false }
bs58 = { version = "0.3", default-features = false, features = ["alloc"] }
iota-constants = { version = "0.2", default-features = false }
iota-conversion = { version = "0.5", default-features = false }
# iota-core = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
iota-core = { git = "https://github.com/Thoralf-M/iota.rs", branch = "works" }
multihash = { version = "0.11", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = { version = "1.0", default-features = false }

identity_core = { path = "../identity_core" }
identity_crypto = { path = "../identity_crypto" }
identity_proof = { path = "../identity_proof" }

[dev-dependencies]
smol-potat = { version = "0.3.3" }
smol = { version = "0.1.18", features = ["tokio02"] }
hex = "0.4.2"
identity_diff = { path = "../identity_diff" }
