[package]
name = "identity_iota"
version = "0.6.0"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity", "did", "ssi"]
license = "Apache-2.0"
readme = "./README.md"
repository = "https://github.com/iotaledger/identity.rs"
rust-version = "1.60"
description = "Framework for Self-Sovereign Identity with IOTA DID."

[dependencies]
identity_agent = { version = "=0.6.0", path = "../identity_agent", default-features = false, optional = true }
identity_core = { version = "=0.6.0", path = "../identity_core", default-features = false }
identity_credential = { version = "=0.6.0", path = "../identity_credential", features = ["validator"], default-features = false }
identity_did = { version = "=0.6.0", path = "../identity_did", default-features = false }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["full"] }

[features]
default = ["revocation-bitmap"]

# Enables revocation with `RevocationBitmap2022`.
revocation-bitmap = ["identity_credential/revocation-bitmap"]

# Enables support for the unstable identity agent.
# Breaking changes to types and functions behind this flag are not covered by semver.
unstable-agent = ["dep:identity_agent"]

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps --workspace --open
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
