[package]
name = "IdentityIota"
edition = "2024.beta"

[dependencies]
MoveStdlib = { git = "https://github.com/iotaledger/kinesis.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "7899dc9ce682c3d0a97f249ce7eaa27b9473b920" }
Sui = { git = "https://github.com/iotaledger/kinesis.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "7899dc9ce682c3d0a97f249ce7eaa27b9473b920" }
StardustTest = { local = "../stardust-test" }

[addresses]
identity_iota = "0x0"
stardust = "0xd2ee1f1775868aed0e8375a7469624e3c39a559b62ab92dddad99544c1d90565"

[dev-dependencies]

[dev-addresses]

