name: Build and run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - 'docs/**'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        project: [identity_account, identity_communication, identity_doc_manager, identity_integration, identity_resolver, identity_schema, identity_vc]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Get current date
      if: matrix.os == 'ubuntu-latest'
      run: echo "::set-env name=CURRENT_DATE::$(date +'%Y-%m-%d')"

    - name: Get current date
      if: matrix.os == 'windows-latest'
      run: echo "::set-env name=CURRENT_DATE::$(Get-Date -Format "yyyy-MM-dd")"

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        # Add date to the cache to keep it up to date
        key: ${{ matrix.project }}-${{ matrix.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ matrix.project }}-${{ matrix.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}

    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        # Add date to the cache to keep it up to date
        key: ${{ matrix.project }}-${{ matrix.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ matrix.project }}-${{ matrix.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}

    - name: Cache cargo target
      uses: actions/cache@v2
      with:
        path: ${{ matrix.project}}/target
        # Add date to the cache to keep it up to date
        key: ${{ matrix.project }}-${{ matrix.os }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ matrix.project }}-${{ matrix.os }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}

    - name: Build ${{ matrix.project }}
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path=${{ matrix.project }}/Cargo.toml --all --release

    - name: Run tests for ${{ matrix.project }}
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=${{ matrix.project }}/Cargo.toml --all --release
