name: Build and run tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/build-and-test.yml'
      - '**.rs'
      - '**.toml'

env:
  RUST_BACKTRACE: full
  SCCACHE_DOWNLOAD_LINK: https://github.com/mozilla/sccache/releases/download
  SCCACHE_VERSION: v0.2.15
  SCCACHE_CACHE_SIZE: 2G
  SCCACHE_IDLE_TIMEOUT: 0
  # SCCACHE_RECACHE: 1 # uncomment to clear sccache cache, then re-comment

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            sccache-path: /home/runner/.cache/sccache
          - os: macos-latest
            sccache-path: /Users/runner/Library/Caches/Mozilla.sccache
          - os: windows-latest
            sccache-path: C:\\Users\\runner\\AppData\\Local\\Mozilla\\sccache\\cache
    env:
      SCCACHE_DIR: ${{ matrix.sccache-path }}
      RUSTC_WRAPPER: sccache

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Get current date
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get current date
        if: matrix.os == 'windows-latest'
        run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Cache cargo
        uses: actions/cache@v2.1.4
        with:
          # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          # Add date to the cache to keep it up to date
          key: ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-
            ${{ matrix.os }}-cargo-${{ github.job }}-
            ${{ matrix.os }}-cargo-

      # Generate Cargo.lock files for build, sccache cache keys.
      # Allows dependencies updated on crates.io between runs to trigger storing an updated cache,
      # which hashing Cargo.toml files alone does not.
      - name: Cargo update
        uses: actions-rs/cargo@v1
        with:
          command: update

      - name: Cache build target
        uses: actions/cache@v2.1.4
        with:
          path: target
          # Add date to the cache to keep it up to date
          key: ${{ matrix.os }}-target-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.os }}-target-${{ github.job }}-
            ${{ matrix.os }}-target-

      - name: Cache sccache
        uses: actions/cache@v2.1.6
        continue-on-error: false
        with:
          path: ${{ matrix.sccache-path }}
          key: ${{ runner.os }}-sccache-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-sccache-${{ github.job }}-
            ${{ runner.os }}-sccache-

      - name: Install sccache (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: |
          SCCACHE_PREFIX="sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl"
          SCCACHE_TAR="${SCCACHE_PREFIX}.tar.gz"
          DOWNLOAD_LINK="${SCCACHE_DOWNLOAD_LINK}/${SCCACHE_VERSION}/${SCCACHE_TAR}"
          curl -L "${DOWNLOAD_LINK}" --output ${SCCACHE_TAR}
          echo "$(curl -L ${DOWNLOAD_LINK}.sha256)  ${SCCACHE_TAR}" | shasum -a 256 --check --status
          tar xzf ${SCCACHE_TAR}
          BIN_DIR="$HOME/.local/bin"
          mkdir -p ${BIN_DIR}
          mv -f ${SCCACHE_PREFIX}/sccache ${BIN_DIR}/sccache
          chmod a+x "${BIN_DIR}/sccache"
          echo ${BIN_DIR} >> $GITHUB_PATH

      - name: Install sccache (macos-latest)
        if: matrix.os == 'macos-latest'
        run: |
          brew update --preinstall
          brew install sccache

      - name: Install sccache (windows-latest)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install sccache
          echo "${HOME}/scoop/apps/sccache/current" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Start sccache
        run: |
          sccache --start-server
          sccache -s

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          # Build the library, tests, and examples without running them to avoid recompilation in the run tests step
          command: test
          args: --all --release --no-run

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --release

      - name: Stop sccache server
        run: sccache --stop-server || true

  build-and-test-libjose:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./libjose/Cargo.toml --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./libjose/Cargo.toml --release

  build-and-test-wasm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            sccache-path: /home/runner/.cache/sccache
    env:
      SCCACHE_DIR: ${{ matrix.sccache-path }}
      CARGO_INCREMENTAL: 0 # disabled to reduce target cache size
      RUSTC_WRAPPER: sccache

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install WASM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Cache cargo
        uses: actions/cache@v2.1.4
        with:
          # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          # Add date to the cache to keep it up to date
          key: ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-
            ${{ matrix.os }}-cargo-${{ github.job }}-
            ${{ matrix.os }}-cargo-

      # Generate Cargo.lock files for build, sccache cache keys.
      # Allows dependencies updated on crates.io between runs to trigger storing an updated cache,
      # which hashing Cargo.toml files alone does not.
      - name: Cargo update
        uses: actions-rs/cargo@v1
        with:
          command: update

      - name: Cache wasm target
        uses: actions/cache@v2.1.4
        with:
          path: bindings/wasm/target
          # Add date to the cache to keep it up to date
          key: ${{ matrix.os }}-wasm-target-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.os }}-wasm-target-${{ github.job }}-
            ${{ matrix.os }}-wasm-target-

      - name: Cache sccache
        uses: actions/cache@v2.1.6
        continue-on-error: false
        with:
          path: ${{ matrix.sccache-path }}
          key: ${{ runner.os }}-sccache-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-sccache-${{ github.job }}-
            ${{ runner.os }}-sccache-

      - name: Install sccache (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: |
          SCCACHE_PREFIX="sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl"
          SCCACHE_TAR="${SCCACHE_PREFIX}.tar.gz"
          DOWNLOAD_LINK="${SCCACHE_DOWNLOAD_LINK}/${SCCACHE_VERSION}/${SCCACHE_TAR}"
          curl -L "${DOWNLOAD_LINK}" --output ${SCCACHE_TAR}
          echo "$(curl -L ${DOWNLOAD_LINK}.sha256)  ${SCCACHE_TAR}" | shasum -a 256 --check --status
          tar xzf ${SCCACHE_TAR}
          BIN_DIR="$HOME/.local/bin"
          mkdir -p ${BIN_DIR}
          mv -f ${SCCACHE_PREFIX}/sccache ${BIN_DIR}/sccache
          chmod a+x "${BIN_DIR}/sccache"
          echo ${BIN_DIR} >> $GITHUB_PATH

      - name: Start sccache
        run: |
          sccache --start-server
          sccache -s

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install wasm-pack
        run: npm install -g wasm-pack

      - name: Install JS dependencies
        run: npm install
        working-directory: bindings/wasm

      - name: Build WASM bindings
        run: npm run build
        working-directory: bindings/wasm

      - name: Build Wasm examples
        run: npm run build:examples
        working-directory: bindings/wasm

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./bindings/wasm/Cargo.toml --release

      - name: Run wasm-bindgen tests # tests annotated with #[wasm_bindgen_test]
        run: wasm-pack test --node
        working-directory: bindings/wasm

      - name: Stop sccache server
        run: sccache --stop-server || true
