name: Build and run tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/build-and-test.yml'
      - '.github/actions'
      - '**.rs'
      - '**.toml'

env:
  RUST_BACKTRACE: full
  SCCACHE_CACHE_SIZE: 2G
  SCCACHE_IDLE_TIMEOUT: 0
  # SCCACHE_RECACHE: 1 # uncomment to clear sccache cache, then re-comment

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            sccache-path: /home/runner/.cache/sccache
          - os: macos-latest
            sccache-path: /Users/runner/Library/Caches/Mozilla.sccache
          - os: windows-latest
            sccache-path: C:\\Users\\runner\\AppData\\Local\\Mozilla\\sccache\\cache
    env:
      SCCACHE_DIR: ${{ matrix.sccache-path }}
      RUSTC_WRAPPER: sccache

    steps:
      - uses: actions/checkout@v2

      - name: Get current date (Windows)
        uses: './.github/actions/utils/get-current-date-windows'
        if: matrix.os == 'windows-latest'

      - name: Get current date (Ubuntu/MacOS)
        uses: './.github/actions/utils/get-current-date-ubuntu-macos'
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'

      - name: Setup Rust and cache
        uses: './.github/actions/rust/rust-setup'
        with:
          os: ${{ runner.os }}
          job: ${{ github.job }}
          sccache-path: ${{ matrix.sccache-path }}
          current-date: ${{ env.CURRENT_DATE }}

      - name: Setup sccache (Ubuntu)
        uses: './.github/actions/rust/sccache/setup-sccache-ubuntu'     
        if: matrix.os == 'ubuntu-latest'
        
      - name: Setup sccache (Windows)
        uses: './.github/actions/rust/sccache/setup-sccache-windows'        
        if: matrix.os == 'windows-latest'

      - name: Setup sccache (MacOS)
        uses: './.github/actions/rust/sccache/setup-sccache-macos'
        if: matrix.os == 'macos-latest'
     
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          # Build the library, tests, and examples without running them to avoid recompilation in the run tests step
          command: test
          args: --all --release --no-run

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --release

      - name: Stop sccache (Windows)
        uses: './.github/actions/rust/sccache/stop-sccache-windows'
        if: matrix.os == 'windows-latest'

      - name: Stop sccache (Ubuntu/MacOS)
        uses: './.github/actions/rust/sccache/stop-sccache-ubuntu-macos'
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'

  build-and-test-libjose:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./libjose/Cargo.toml --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./libjose/Cargo.toml --release

  build-and-test-wasm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            sccache-path: /home/runner/.cache/sccache
    env:
      SCCACHE_DIR: ${{ matrix.sccache-path }}
      CARGO_INCREMENTAL: 0 # disabled to reduce target cache size
      RUSTC_WRAPPER: sccache

    steps:
      - uses: actions/checkout@v2

      - name: Get current date (Ubuntu/MacOS)
        uses: './.github/actions/utils/get-current-date-ubuntu-macos'
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'

      - uses: './.github/actions/rust/rust-setup'
        name: rust-setup
        with:
          os: ${{ runner.os }}
          job: ${{ github.job }}
          sccache-path: ${{ matrix.sccache-path }}
          current-date: ${{ env.CURRENT_DATE }}
          target-cache-path: bindings/wasm/target

      - name: Install WASM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
        
      - name: Setup sccache (Ubuntu)
        uses: './.github/actions/rust/sccache/setup-sccache-ubuntu'
        if: matrix.os == 'ubuntu-latest'

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install wasm-pack
        run: npm install -g wasm-pack

      - name: Install JS dependencies
        run: npm install
        working-directory: bindings/wasm

      - name: Build WASM bindings
        run: npm run build
        working-directory: bindings/wasm

      - name: Build Wasm examples
        run: npm run build:examples
        working-directory: bindings/wasm

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./bindings/wasm/Cargo.toml --release

      - name: Run wasm-bindgen tests # tests annotated with #[wasm_bindgen_test]
        run: wasm-pack test --node
        working-directory: bindings/wasm

      - name: Stop sccache (Ubuntu/MacOS) 
        uses: './.github/actions/rust/sccache/stop-sccache-ubuntu-macos'
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
