name: Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - release/*
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: BRANCHNAME=$(git rev-parse --abbrev-ref HEAD)
      - run: |
          NEXTVERSION=
          if [[ $BRANCHNAME == release/* ]]; then
            NEXTVERSION=${BRANCHNAME##*/}
          fi
          echo 'NEXTVERSION=$(NEXTVERSION)'
      - name: Run box version	    
        uses: docker://githubchangeloggenerator/github-changelog-generator
        with:
          args: --user eike-hass --project identity.rs --token ${{ secrets.GITHUB_TOKEN }} --no-author --future-release $(NEXTVERSION) --verbose
      - run: cat CHANGELOG.md
      - run: |
          if [[ $(git diff --stat) == '' ]]; then
            echo 'CHANGELOG.md unmodified'
            exit 0
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add CHANGELOG.md
          git commit -m "generate Changelog"
          git push

      
