name: Coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/coverage.yml'
      - '.github/workflows/scripts/coverage.sh'
      - '**.rs'
      - '**.toml'

jobs:
  coverage:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-07-05
          override: true
          components: llvm-tools-preview
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: 0.3.3
      - uses: actions-rs/install@v0.1
        with:
          crate: rustfilt
          version: 0.2.1
      - name: Run test coverage
        run: bash .github/workflows/scripts/coverage.sh
      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/coverage.info
