name: Examples

on:
  schedule:
    - cron: '0 0 * * *' # run at midnight every day
  workflow_dispatch:

jobs:
  rust-examples:
    # owner/repository of workflow has to be static, see https://github.community/t/env-variables-in-uses/17466
    uses: iotaledger/identity.rs/.github/workflows/shared-run-rust-examples.yml@chore/run-examples-on-dependabot-alerts

  wasm-examples:
    # owner/repository of workflow has to be static, see https://github.community/t/env-variables-in-uses/17466
    uses: iotaledger/identity.rs/.github/workflows/shared-run-wasm-examples.yml@chore/run-examples-on-dependabot-alerts
