name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - epic/*
    paths:
      - '.github/workflows/format.yml'
      - '**.rs'
      - '**.toml'

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      # we use nightly to get access to advanced format capabilities
      - name: Install rustfmt with nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Install cargo-license-template
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-license-template

      - name: Install dprint
        run: npm install -g dprint
        #run: cargo install dprint # installing from source is slow, ~5 minutes

      - name: core fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: wasm fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./bindings/wasm/Cargo.toml --all -- --check

      # Deactivated while the crate is broken, which is the case due to the removal of identity_account_storage.
      # - name: stronghold-nodejs fmt check
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: --manifest-path ./bindings/stronghold-nodejs/Cargo.toml --all -- --check

      - name: libjose fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./libjose/Cargo.toml --all -- --check

      # Use `dprint` to check Cargo.toml formatting.
      # To fix, run `dprint fmt` locally.
      - name: Cargo.toml fmt check
        run:
          dprint check

      - name: cargo-license-template check
        run: cargo license-template --template .license_template --ignore .license_template_ignore --verbose
