name: gRPC publish to dockerhub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish under, defaults to latest'
        required: false
        default: latest
      branch:
        description: 'Branch to run publish from'
        required: true
      dry-run:
        description: 'Run in dry-run mode'
        type: boolean
        required: false
        default: true

jobs:
  push_to_registry:
    environment: release
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.IOTALEDGER_DOCKER_USERNAME }}
        password: ${{ secrets.IOTALEDGER_DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: bindings/grpc/Dockerfile
        push: ${{ !inputs.dry-run }}
        labels: iotaledger/identity-grpc:${{ inputs.tag }}

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae
      with:
        username: ${{ secrets.IOTALEDGER_DOCKER_USERNAME }}
        password: ${{ secrets.IOTALEDGER_DOCKER_PASSWORD }}
        repository: iotaledger/identity-grpc
        readme-filepath: ./bindigns/grpc/README.md
        short-description: ${{ github.event.repository.description }}

