name: Changelog

on:
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker info
      - name: Run box version	    
        uses: docker://githubchangeloggenerator/github-changelog-generator
        with:
          CMD: --help

      # - name: Commit files
      #   env:
      #     CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
      #     CI_EMAIL: ${{ secrets.YOUR_GITHUB_EMAIL }}
      #   run: |
      #     git config --local user.email "$CI_EMAIL"
      #     git config --local user.name "$CI_USER"
      #     git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

      # - name: Push changes
      #   if: env.push == 'true'
      #   env:
      #     CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
      #     CI_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN or GITHUB_TOKEN }}
      #   run: |
      #     git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master

      
