name: Publish

on:
  workflow_dispatch:

jobs:
  wasm:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install WASM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install JS dependencies
        run: yarn
        working-directory: bindings/wasm

      - name: Build WASM bindings
        run: yarn build
        working-directory: bindings/wasm

      - name: Publish WASM bindings to NPM
        run: yarn publish --access public --loglevel silly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: bindings/wasm
