name: Release

on:
  workflow_dispatch:
  create:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - name: Get current branch name
        run: |
          BRANCHNAME=$(git rev-parse --abbrev-ref HEAD)
          echo BRANCHNAME=$BRANCHNAME
          echo BRANCHNAME=$BRANCHNAME >> $GITHUB_ENV
          CURRENT_TAG=$(git describe --exact-match HEAD)
          echo CURRENT_TAG=$CURRENT_TAG

      
