name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - name: Prepare repository
        run: |
          echo GITHUB_REF=$GITHUB_REF
          if [[ $GITHUB_REF != refs/tags/v* ]]; then
            echo unrecognized version '$GITHUB_REF'
            exit 1
          fi

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          prerelease: false
      
      - name: Release to npm
        uses: './.github/actions/release/release-npm'
      
