name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "dev-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare repository
        run: |
          GITHUB_REF=${{ env.GITHUB_REF }}

          if [[ $GITHUB_REF == dev-* ]]; then
            IS_DEV_VERSION=true
          elif [[ $GITHUB_REF == v* ]]; then
            IS_DEV_VERSION=false
          else
            echo unrecognized version '$GITHUB_REF'
            exit 1
          fi

          echo IS_DEV_VERSION=$IS_DEV_VERSION
          echo IS_DEV_VERSION=$IS_DEV_VERSION >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          prerelease: ${{ env.IS_DEV_VERSION }}
      
