name: Rust deploy crate docs

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run publish from"
        required: true
      dry-run:
        description: "Run in dry-run mode"
        type: boolean
        required: false
        default: true

jobs:
  docs:
    name: Generate crate documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          ref: ${{ github.event.inputs.branch || github.event.repository.default_branch }}
      - name: Generate documentation
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.1
        with:
          command: doc
          args: --workspace --no-deps

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: ${{ !inputs.dry-run }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true
