name: Shared / Create Dev Release PR

on:
  workflow_call:
    inputs:
      tag-prefix:
        description: "will be prepended to tag-base"
        required: false
        type: string
      tag-base:
        description: "the base version of the dev release"
        required: true
        type: string
      tag-postfix:
        description: "will be appended to tag-base, marks the kind of dev release"
        required: true
        type: string
      main-tag-regex:
        description: "the regex to find all related main releases"
        required: true
        type: string
      changelog-path:
        description: "path to the changelog file"
        required: false
        default: ./CHANGELOG.md
        type: string
      changelog-config-path:
        description: "path to the changelog config"
        required: true
        type: string
      pr-body-text:
        description: "text to be included in the PR"
        required: false
        type: string
      release-target:
        description: "target of the release (rust|wasm)"
        required: true
        type: string
    secrets:
      GPG_PRIVATE_KEY:
        description: "GPG private key for signing commits and tags"
        required: true
      GPG_PASSPHRASE:
        description: "GPG private passphrase for signing commits and tags"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
          ref: dev

      - name: Validate version
        run: |
          VERSION=${{ inputs.tag-prefix }}${{ inputs.tag-base }}
          if ! [[ $VERSION =~ ${{ inputs.main-tag-regex }} ]]; then
            echo unrecognized version $VERSION, must match ${{ inputs.main-tag-regex }}
            exit 1
          fi

      - name: Determine Next Version
        run: |

          TAG_PREFIX=${{ inputs.tag-prefix }}
          TAG_BASE=${{ inputs.tag-base }}
          TAG_POSTFIX=${{ inputs.tag-postfix }}

          # joins an array with a delimiter
          function join_by { local IFS="$1"; shift; echo "$*"; }

          # takes a string and increments the last number
          updateVersion()
          {
            [[ ${1} =~ ^(.*[^0-9])?([0-9]+)$ ]]  && \
              [[ ${#BASH_REMATCH[1]} -gt 0 ]] && \
                printf "%s%0${#BASH_REMATCH[2]}d" "${BASH_REMATCH[1]}" "$((10#${BASH_REMATCH[2]} + 1 ))" || \
                printf "%0${#BASH_REMATCH[2]}d" "$((10#${BASH_REMATCH[2]} + 1))" || \
              printf "${1}"
          }

          # create a list of tags that are unrelated to the current release
          ALL_TAGS=$(git tag --sort=creatordate -l)
          temp_array=()
          for value in ${ALL_TAGS[@]}
          do
              if ! [[ $value == $TAG_PREFIX$TAG_BASE$TAG_POSTFIX* || $value =~ ${{ inputs.main-tag-regex }} ]]; then
                temp_array+=($value)
              fi
          done
          UNRELATED_TAGS=$(join_by , "${temp_array[@]}")
          unset temp_array
          echo UNRELATED_TAGS=$UNRELATED_TAGS
          
          # determine if there is a previous dev version or this is the first dev release
          LATEST_DEV_TAG=$(git tag --list --sort=-version:refname "$TAG_PREFIX$TAG_BASE$TAG_POSTFIX*" | head -n 1)
          echo LATEST_DEV_TAG=$LATEST_DEV_TAG
          if [[ $LATEST_DEV_TAG == '' ]]; then
            NEW_DEV_TAG=$TAG_PREFIX$TAG_BASE$TAG_POSTFIX
            NEW_DEV_TAG+="1"
            LATEST_DEV_TAG=$NEW_DEV_TAG
            FIRST="--exclude-tags "
            SECOND=$UNRELATED_TAGS
            EXCLUDE_ARG=$FIRST$SECOND
          else
            NEW_DEV_TAG=$(updateVersion $LATEST_DEV_TAG)

            # exclude dev version already merged in main
            ALL_DEV_TAGS_IN_MAIN=$(git tag -l "$TAG_PREFIX$TAG_BASE$TAG_POSTFIX*" --merged $(git log -n 1 refs/remotes/origin/main --pretty=format:"%H"))
            temp_array=()
            for value in "${ALL_DEV_TAGS_IN_MAIN[@]}"
            do
                [[ $value != $LATEST_DEV_TAG ]] && temp_array+=($value)
            done
            FIRST="--exclude-tags "
            SECOND=$(join_by , "${temp_array[@]}")
            if [[ $SECOND != '' ]]; then
              SECOND+=,
            fi
            THIRD=$UNRELATED_TAGS
            unset temp_array
            EXCLUDE_ARG=$FIRST$SECOND$THIRD
          fi
          
          # set variables
          echo NEW_DEV_TAG=$NEW_DEV_TAG
          NEXTVERSION=$NEW_DEV_TAG

          echo NEXTVERSION=$NEXTVERSION
          echo NEXTVERSION=$NEXTVERSION >> $GITHUB_ENV
          
          NEXTVERSION_WITHOUT_PREFIX=$(echo "$NEXTVERSION" | sed "s/$TAG_PREFIX*//")
          echo NEXTVERSION_WITHOUT_PREFIX=$NEXTVERSION_WITHOUT_PREFIX
          echo NEXTVERSION_WITHOUT_PREFIX=$NEXTVERSION_WITHOUT_PREFIX >> $GITHUB_ENV

          echo EXCLUDE_ARG=$EXCLUDE_ARG
          echo EXCLUDE_ARG=$EXCLUDE_ARG >> $GITHUB_ENV

      - name: Prepare Repository
        run: |
          GITHUB_REPOSITORY_USER=$( echo $GITHUB_REPOSITORY | awk -F'/' '{print $1}') 
          GITHUB_REPOSITORY_PROJECT=$( echo $GITHUB_REPOSITORY | awk -F'/' '{print $2}') 

          echo GITHUB_REPOSITORY_USER=$GITHUB_REPOSITORY_USER
          echo GITHUB_REPOSITORY_PROJECT=$GITHUB_REPOSITORY_PROJECT

          echo GITHUB_REPOSITORY_USER=$GITHUB_REPOSITORY_USER >> $GITHUB_ENV
          echo GITHUB_REPOSITORY_PROJECT=$GITHUB_REPOSITORY_PROJECT >> $GITHUB_ENV

      - name: Run github-changelog-generator
        uses: docker://githubchangeloggenerator/github-changelog-generator
        with:
          args: >
            --output ${{ inputs.changelog-path }}
            --config-file ${{ inputs.changelog-config-path }}
            --user ${{ env.GITHUB_REPOSITORY_USER }}
            --project ${{ env.GITHUB_REPOSITORY_PROJECT }} 
            --token ${{ secrets.GITHUB_TOKEN }} 
            --future-release ${{ env.NEXTVERSION }} 
            ${{ env.EXCLUDE_ARG }}

      - name: Log ${{ inputs.changelog-path }}
        run: cat ${{ inputs.changelog-path }}

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Commit changelog
        run: |
          git add .
          if [[ $(git diff --stat --staged) == '' ]]; then
            echo 'repository unmodified'
            exit 1
          fi
          git commit -m "generate changelog"

      - uses: actions-rs/toolchain@v1
        if: ${{inputs.release-target == 'rust' || inputs.release-target == 'wasm'}}
        with:
          toolchain: stable

      - name: Install cargo-release
        uses: actions-rs/cargo@v1
        if: ${{inputs.release-target == 'rust' || inputs.release-target == 'wasm'}}
        with:
          command: install
          args: cargo-release

      - name: Install cargo-edit # to use cargo add
        uses: actions-rs/cargo@v1
        if: ${{inputs.release-target == 'rust'}}
        with:
          command: install
          args: cargo-edit

      - name: Replace identity (dev) version in Wasm bindings
        if: ${{inputs.release-target == 'rust'}}
        run: |
          cd bindings/wasm
          cargo add identity@=${{ env.NEXTVERSION_WITHOUT_PREFIX }} --path=../../identity

      - name: Commit changes
        if: ${{inputs.release-target == 'rust'}}
        run: |
          git add .
          if [[ $(git diff --stat --staged) == '' ]]; then
            echo 'repository unmodified'
            exit 1
          fi
          git commit -m "bump version"
      
      - name: Bump Rust (dev) version
        # cargo-release creates a signed commit automatically
        if: ${{inputs.release-target == 'rust'}}
        run: |
          cargo release --workspace --config ./release.toml --no-tag --no-publish --no-push --no-confirm ${{ env.NEXTVERSION_WITHOUT_PREFIX }} --execute

      - name: Run cargo-release
        if: ${{inputs.release-target == 'wasm'}}
        run: |
          cd bindings/wasm
          cargo release --no-tag --no-publish --no-push --no-confirm ${{ env.NEXTVERSION_WITHOUT_PREFIX }} --execute

      - uses: actions/setup-node@v2
        if: ${{inputs.release-target == 'wasm'}}
        with:
          node-version: '16'

      - name: Replace Version
        if: ${{inputs.release-target == 'wasm'}}
        run: |
          cd bindings/wasm
          npm version ${{ env.NEXTVERSION_WITHOUT_PREFIX }}

      - name: Commit npm version bump
        if: ${{inputs.release-target == 'wasm'}}
        run: |
          git add .
          if [[ $(git diff --stat --staged) == '' ]]; then
            echo 'repository unmodified'
            exit 1
          fi
          git commit -m "bump version"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: release/${{ env.NEXTVERSION }}
          delete-branch: true
          title: 'Release ${{ env.NEXTVERSION }}'
          body: |
            This automatically generated PR contains changes for the `${{ env.NEXTVERSION }}` version.
            ${{inputs.pr-body-text}}
            If you discover any mistakes fix them with commits on this branch. If you want to abort the release simply close the PR. 
          labels: |
            No changelog


      
