name: Test Docs Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - epic/*
      - support/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Wiki Build
        working-directory: documentation
        run: |
          yarn install --immutable
          yarn build

      # docs.rs also uses nightly so it makes sense to mirror that
      - name: Setup Rust
        uses: './.github/actions/rust/rust-setup'
        with:
          toolchain: nightly
          os: ${{ runner.os }}
          job: ${{ github.job }}
      
      - name: Test Rust Documentation
        env:
          RUSTDOCFLAGS: "-D warnings --cfg docsrs"
        run: cargo +nightly doc --all-features --no-deps --workspace
