name: Test Docs Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - epic/*
      - support/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Wiki Build
        working-directory: documentation
        run: |
          yarn install --immutable
          yarn build

      # docs.rs also uses nightly so it makes sense to mirror that
      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Test Rust Documentation
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: "-D warnings --cfg docsrs"
        with:
          command: doc
          toolchain: nightly
          args: --all-features --no-deps --workspace
