name: GitHub Pages

on:
  pull_request:
    branches: [ docs/fixBuild, dev,   main]
  push:
    branches: [ docs/fixBuild, dev,  main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Test Build
        run: |
          cd documentation
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run setup
          cd local-wiki/iota-wiki
          npm run build
