name: Wasm Automatic Release and Publish

# Automatically publishes the latest Wasm bindings version to npm when a release PR is merged.
# Does NOT create a GitHub release.
on:
  pull_request:
    branches:
      - dev
      - support/wasm-v*
    types: [closed]
jobs:
  call-create-release-workflow:
    if: github.event.pull_request.merged == true
    # owner/repository of workflow has to be static, see https://github.community/t/env-variables-in-uses/17466
    uses: iotaledger/identity.rs/.github/workflows/shared-release.yml@dev
    with:
      changelog-config-path: ./bindings/wasm/.github_changelog_generator
      dev-tag-regex: ^wasm-v[0-9]+\.[0-9]+\.[0-9]+-(dev)\.\d*$
      main-tag-regex: ^wasm-v[0-9]+\.[0-9]+\.[0-9]+$
      create-github-release: false
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  release:
    runs-on: ubuntu-latest
    needs: call-create-release-workflow
    if: ${{ needs.call-create-release-workflow.outputs.is-release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release to npm
        uses: './.github/actions/publish/publish-wasm'
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ needs.call-create-release-workflow.outputs.is-dev-release && 'dev' }}